name: releasebuild

on:
  push:
   tags:
    - v*

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout â¬‡
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Docker layer cache âš™
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: omadasitedns-docker-cache-{hash}
          restore-keys: |
            omadasitedns-docker-cache-

      - name: Setup Go âš™
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: ~1.17
      
      - name: Setup QEMU âš™
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      
      - name: Setup Docker Buildx âš™
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Registry ðŸ”’
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run GoReleaser ðŸ’¨
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}